apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: NodePort
  externalIPs:
  - xxx.xxx.xxx.xxx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: api-manager
    port: 9000
    targetPort: 80
    protocol: TCP
  - name: api-manager-gateway
    port: 9002
    targetPort: 80
    protocol: TCP
  - name: observability
    port: 9004
    targetPort: 80
    protocol: TCP
  - name: observability-api
    port: 9006
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
